### ISSUE TITLE
SDP support on windows

### ISSUE THREAD

**Issue by jakobhu** [oxfordcontrol/Clarabel.cpp#50]
Is SDP supported on windows ?

I've followed the README guide and got the cpp examples running; however, I've had no success with enabling SDP support.
So far the sdp-mkl option seems to compile - except it lacks the libiomp5md.dll. I've manually added that to the output directory - and also tried a couple of different versions. Still, when running the  cpp_example_sdp.exe The outcome is consistently this:

```
Intel MKL ERROR: Parameter 6 was incorrect on entry to DSYEVR.
thread '<unnamed>' panicked at C:\src\Clarabel.cpp\Clarabel.rs\src\solver\core\cones\psdtrianglecone.rs:114:38:
Eigval error: Eigen(-6)

```

I've tried to use the sdp-openblas option as well, however that fails with the message:

`    Non-vcpkg builds are not supported on Windows. You must use the 'system' feature.
`
so I tried to install openblas using vcpkg : 

`vcpkg.exe install openblas 
`

still without any progress, and I have no idea what the 'system' feature is.

Any ideas on how to make SDP work with windows ?

**Comment by goulart-paul** [comment]
The issue here might be related to MKLs expectations about how matrix indices are typed, since there are different library versions for 32 or 64 bit and (I think?) signed vs unsigned indices.

I think this problem is has been fixed on the main clarabel.rs branch, but we have not yet made a release since it was committed.     It was this commit specifically:

https://github.com/oxfordcontrol/Clarabel.rs/commit/7036899fda1c3c95bbee894bd9babce4f2e66c40#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R85

**Comment by jakobhu** [comment]
Thank you! I can confirm that the change makes the "cpp_example_sdp.exe" example work as expected on Windows (provided that the libiomp5md.dll library is in place).

**Comment by goulart-paul** [comment]
OK, thanks for confirming.   I will close this issue, and the fix will be included in our next release.
